/**
 * CONFIG - Auto-generated by build.js
 * Client: Oconee County Chamber of Commerce
 * Do not edit manually - modify clients/oconee/client.json instead
 */

const CONFIG = {
    "mapbox": {
        "accessToken": "pk.eyJ1IjoicnlhbmRvbHBoanIiLCJhIjoiY21sOHI2OXRvMGE2ejNtcTMyajh0bWJtNCJ9.fDd6RAIarBzArdbZu8gfCA",
        "style": "mapbox://styles/mapbox/streets-v12",
        "center": [
            -82.9532,
            34.7
        ],
        "zoom": 12,
        "minZoom": 3,
        "maxZoom": 18
    },
    "client": {
        "name": "Chamber of Commerce Interactive Map",
        "logoPath": "assets/logos/client-logo.png",
        "logoAlt": "Oconee County Chamber of Commerce Logo"
    },
    "dolphLogo": {
        "logoPath": "assets/logos/dolph-logo.jpg",
        "logoAlt": "Dolph Map Company",
        "link": "https://dolphmap.com",
        "contact": {
            "name": "Marsha Duvall",
            "phone": "(954) 695-0327",
            "email": "mduvall@dolphmap.com"
        }
    },
    "banners": {
        "banner1": null,
        "banner2": [],
        "slideshow": {
            "interval": 5000,
            "fadeTransition": 1000
        }
    },
    "data": {
        "csvPath": "data/advertisers.csv"
    },
    "markers": {
        "defaultColor": "#1a5276",
        "clusterEnabled": false,
        "customIcon": null
    },
    "cityLabel": {
        "name": "OCONEE COUNTY",
        "position": [
            -83.0638,
            34.79
        ],
        "hideFromDefaultLabels": [
            "Seneca",
            "Walhalla",
            "Westminster",
            "Salem",
            "West Union",
            "Fair Play",
            "Newry",
            "Long Creek",
            "Mountain Rest"
        ],
        "hideAtZoom": 14,
        "additionalLabels": [
            {
                "name": "SENECA",
                "position": [
                    -82.9532,
                    34.675
                ],
                "fontSize": "14px",
                "hideAtZoom": 14
            },
            {
                "name": "WALHALLA",
                "position": [
                    -83.0638,
                    34.7648
                ],
                "fontSize": "14px",
                "hideAtZoom": 14
            },
            {
                "name": "WESTMINSTER",
                "position": [
                    -83.0965,
                    34.6648
                ],
                "fontSize": "14px",
                "hideAtZoom": 14
            },
            {
                "name": "SALEM",
                "position": [
                    -82.973,
                    34.891
                ],
                "fontSize": "14px",
                "hideAtZoom": 14
            },
            {
                "name": "WEST UNION",
                "position": [
                    -83.0532,
                    34.726
                ],
                "fontSize": "14px",
                "hideAtZoom": 14
            },
            {
                "name": "FAIR PLAY",
                "position": [
                    -83.014,
                    34.512
                ],
                "fontSize": "13px",
                "hideAtZoom": 14
            },
            {
                "name": "NEWRY",
                "position": [
                    -82.907,
                    34.729
                ],
                "fontSize": "13px",
                "hideAtZoom": 14
            },
            {
                "name": "LONG CREEK",
                "position": [
                    -83.256,
                    34.782
                ],
                "fontSize": "13px",
                "hideAtZoom": 14
            },
            {
                "name": "MOUNTAIN REST",
                "position": [
                    -83.156,
                    34.871
                ],
                "fontSize": "13px",
                "hideAtZoom": 14
            }
        ]
    },
    "chamberCallout": {
        "position": [
            -82.9532,
            34.715
        ],
        "showAtZoom": 12
    },
    "countyBorder": {
        "geojsonPath": "assets/oconee-county-boundary.geojson",
        "lineColor": "#061550",
        "lineWidth": 3,
        "lineOpacity": 0.7
    }
};

// Verify that CONFIG is properly defined
if (typeof CONFIG === 'undefined') {
    console.error('ERROR: CONFIG object is not defined!');
}
